import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"

const testimonials = [
  {
    name: "Dr. Sarah Johnson",
    role: "Professor of Biology",
    content:
      "Paper to X has revolutionized how I share my research. The ability to quickly transform complex papers into engaging presentations is invaluable.",
  },
  {
    name: "Mark Thompson",
    role: "PhD Candidate in Physics",
    content:
      "As a busy researcher, Paper to X saves me countless hours. The podcast feature allows me to share my work with a broader audience effortlessly.",
  },
  {
    name: "Dr. Emily Chen",
    role: "Research Scientist",
    content:
      "The graphical abstracts generated by Paper to X have significantly increased the visibility of my publications. It's an essential tool for modern researchers.",
  },
]

export function Testimonials() {
  return (
    <section className="py-12">
      <h2 className="text-3xl font-bold text-center mb-8">What Our Users Say</h2>
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        {testimonials.map((testimonial, index) => (
          <Card key={index} className="hover-lift transition-all duration-300 rounded-apple">
            <CardHeader>
              <CardTitle>{testimonial.name}</CardTitle>
              <p className="text-sm text-muted-foreground">{testimonial.role}</p>
            </CardHeader>
            <CardContent>
              <p className="text-sm">{testimonial.content}</p>
            </CardContent>
          </Card>
        ))}
      </div>
    </section>
  )
}

